import assets from "./assets";

const NFTData = [
  {
    id: "NFT-01",
    name: "Big Time Rush",
    when: "Feb. 28, 2023 - 21h",
    creator: "Chamorro City Hall",
    price: "From 48.61",
    description:
      "Big Time Rush became a sensation in 2009 since the release of the Nickelodeon television series Big Time Rush. The show was a huge success and catapulted the group to real-life stardom as they released 3 studio albums and performed in different parts of the world, including five tours from 2011 to 2014. In June 2020, the band held a surprise virtual meeting to celebrate the 10th anniversary of their smash hit 'Worldwide,' sparking mass hysteria among their fans and the media. In March 2021, all four seasons of Nickelodeon's Big Time Rush were added to Netflix and the band went viral once again, increasing fan demand for an official reunion. Soon after, the band announced that they would team up for two special live shows in New York and Chicago, which sold out in a matter of minutes, exceeding expectations and proving the power of the band's devoted fandom. Now, with the launch of her Forever Tour and the release of all new music, including the hit singles 'Honey', 'Fall', 'Not Giving You Up' and 'Call It Like I see It,' fans can expect to see much more of the group in the years to come.",
    image: assets.nft01,
    bids: [
      {
        id: "BID-11",
        name: "Stage 1",
        price: 48.61,
        image: assets.WaveStage1,
        date: "Sold out",
      },
      {
        id: "BID-12",
        name: "Stage 2",
        price: 60.71,
        image: assets.WaveStage2,
        date: "Available",
      },
      {
        id: "BID-13",
        name: "Stage 3",
        price: 77.69,
        image: assets.WaveStage3,
        date: "Available",
      },
    ],
  },
  {
    id: "NFT-02",
    name: "Romeo Santos",
    when: "Mar. 7, 2023 - 20h",
    creator: "Movistar Arena",
    price: "From 48.87",
    description:
      "The King of Bachata will be in Bogotá in March 2023 presenting his latest album 'Fórmula Vol.3'. The autor of musical hits such as 'Siri', 'Me Extraño and 'Pañielo will finally be in Movistar Arena, the wait is over for the thousands of fans in Colombia of the King of Bachata Romeo Santos.",
    image: assets.nft03,
    bids: [
      {
        id: "BID-21",
        name: "Section 301-302-318-319",
        price: 48.87,
        image: assets.WaveStage1,
        date: "Sold Out",
      },
      {
        id: "BID-22",
        name: "Section 201-219-303-304-316-317",
        price: 73.30,
        image: assets.WaveStage2,
        date: "Sold Out",
      },
      {
        id: "BID-23",
        name: "Section 305-315",
        price: 85.52,
        image: assets.WaveStage3,
        date: "Sold Out",
      },
      {
        id: "BID-24",
        name: "Section 206-214",
        price: 146.60,
        image: assets.WaveStage4,
        date: "Sold Out",
      },
      {
        id: "BID-25",
        name: "Section 202-205-215-218",
        price: 171.03,
        image: assets.WaveStage5,
        date: "Available",
      },
      {
        id: "BID-26",
        name: "Fan Grandstand",
        price: 293.20,
        image: assets.WaveStage6,
        date: "Sold Out",
      },
      {
        id: "BID-27",
        name: "VIP 1",
        price: 2443.34,
        image: assets.WaveStage1,
        date: "Sold Out",
      },
      {
        id: "BID-28",
        name: "VIP 2",
        price: 3420.67,
        image: assets.WaveStage2,
        date: "Available",
      },
      {
        id: "BID-29",
        name: "VIP 3",
        price: 4398.01,
        image: assets.WaveStage3,
        date: "Available",
      },
    ],
  },
  {
    id: "NFT-03",
    name: "Imagine Dragons",
    when: "Mar. 12, 2023 - 21h",
    creator: "Coliseo Live",
    price: "From 28.05",
    description:
      "Imagine Dragons, a Grammy Award-winning multi-platinum rock band, announces its arrival in Colombia with its Mercury World Tour, a tour produced by Live Nation. It will be the fourth concert tour of the American alternative rock band where they will perform live their fifth and sixth studio albums Mercury – Act 1 and Act 2, released in 2021 and 2022 respectively. This world tour began in February of this year in the United States, then set foot in Europe visiting Prague, Vienna, the United Kingdom, followed by Canada and recently the band announced, through their social networks, two additional dates for their tour in South Africa and the long-awaited date on which he will visit Colombia for the second time, after seven years of absence.",
    image: assets.nft02,
    bids: [
      {
        id: "BID-31",
        name: "Section 121-124",
        price: 28.05,
        image: assets.WaveStage1,
        date: "Sold Out",
      },
      {
        id: "BID-32",
        name: "Section 105-108",
        price: 42.07,
        image: assets.WaveStage2,
        date: "Sold Out",
      },
      {
        id: "BID-33",
        name: "Section 100-104",
        price: 63.95,
        image: assets.WaveStage3,
        date: "Available",
      },
      {
        id: "BID-34",
        name: "Platea 2",
        price: 92.50,
        image: assets.WaveStage4,
        date: "Available",
      },
      {
        id: "BID-35",
        name: "Section 109-120",
        price: 107.29,
        image: assets.WaveStage5,
        date: "Available",
      },
      {
        id: "BID-36",
        name: "Platea 1",
        price: 122.59,
        image: assets.WaveStage6,
        date: "Available",
      },
    ],
  },
  {
    id: "NFT-04",
    name: "Paramore",
    when: "Mar. 14, 2023 - 21h",
    creator: "Movistar Arena",
    price: "From 48.87",
    description:
      "The renowned band Paramore, led by Hayley Williams, surprised their millions of fans with the news of their Latin American tour. The longing of their fans was heard and, through their official Twitter account, the band announced the dates on which they will be in the main cities of Peru, Argentina, Brazil, Chile and, of course, Colombia.",
    image: assets.nft04,
    bids: [
      {
        id: "BID-41",
        name: "Section 301-302-318-319",
        price: 48.87,
        image: assets.WaveStage1,
        date: "Sold Out",
      },
      {
        id: "BID-42",
        name: "Section 201-219-303-304-316-317",
        price: 73.30,
        image: assets.WaveStage2,
        date: "Sold Out",
      },
      {
        id: "BID-43",
        name: "Section 305-315",
        price: 85.52,
        image: assets.WaveStage3,
        date: "Sold Out",
      },
      {
        id: "BID-44",
        name: "Section 206-214",
        price: 146.60,
        image: assets.WaveStage4,
        date: "Sold Out",
      },
      {
        id: "BID-45",
        name: "Section 202-205-215-218",
        price: 171.03,
        image: assets.WaveStage5,
        date: "Available",
      },
      {
        id: "BID-46",
        name: "Fan Grandstand",
        price: 293.20,
        image: assets.WaveStage6,
        date: "Sold Out",
      },
      {
        id: "BID-47",
        name: "VIP 1",
        price: 2443.34,
        image: assets.WaveStage1,
        date: "Sold Out",
      },
      {
        id: "BID-48",
        name: "VIP 2",
        price: 3420.67,
        image: assets.WaveStage2,
        date: "Available",
      },
      {
        id: "BID-49",
        name: "VIP 3",
        price: 4398.01,
        image: assets.WaveStage3,
        date: "Available",
      },
    ],
  },
  {
    id: "NFT-05",
    name: "Estereo Picnic",
    when: "March 23, 24, 25 & 26",
    creator: "Campo de Golf Briceño 18",
    price: "From 250.28",
    description:
      "In 2022 we live the FEP Comeback and in 2023 we will live a great edition where we will celebrate that Lxs Distintxs Somos Todxs. There will be more than 50 hours of live music, of unfading memories, of strengthening friendships, relationships and our own freedom. We are all here and we will endorse it on March 23, 24, 25 and 26, 2023 in the twelfth edition of the Picnic Stereo Festival. The Briceño 18 Golf Course will once again be the receptacle of fulfilled dreams, eternal dance, human diversity, the here and now. The call today is to the Believers of 2023 and of these four days of monumental liberation. You already know, you have to separate the days 23, 24, 25 and 26 of March 2023 in the calendar and buy the Believers combo from September 12/15. For now, cancel the trips, move the birthday, postpone the marriage or if not, celebrate it all in A Different World.",
    image: assets.nft05,
    bids: [
      {
        id: "BID-51",
        name: "3 days Stage 1",
        price: 250.28,
        image: assets.WaveStage1,
        date: "Available",
      },
      {
        id: "BID-52",
        name: "3 days Stage 2",
        price: 275.14,
        image: assets.WaveStage2,
        date: "Available",
      },
      {
        id: "BID-53",
        name: "4 days Stage 1",
        price: 300.21,
        image: assets.WaveStage3,
        date: "Available",
      },
      {
        id: "BID-54",
        name: "4 days Stage 2",
        price: 325.50,
        image: assets.WaveStage4,
        date: "Available",
      },
      {
        id: "BID-55",
        name: "3 days VIP",
        price: 538.17,
        image: assets.WaveStage5,
        date: "Available",
      },
      {
        id: "BID-56",
        name: "4 days VIP",
        price: 675.85,
        image: assets.WaveStage6,
        date: "Available",
      },
    ],
  },
  {
    id: "NFT-06",
    name: "Hombres G",
    when: "Apr. 15, 2023 - 21h",
    creator: "Movistar Arena",
    price: "From 25.71",
    description:
      "The Madrid quartet Hombres G needs no introduction. Their music has broken all generational barriers and after 40 years of experience they have not only become a rock classic in Spanish, but they continue to reap success.",
    image: assets.nft06,
    bids: [
      {
        id: "BID-61",
        name: "Section 301-302-318-319",
        price: 48.87,
        image: assets.WaveStage1,
        date: "Sold Out",
      },
      {
        id: "BID-62",
        name: "Section 201-219-303-304-316-317",
        price: 73.30,
        image: assets.WaveStage2,
        date: "Sold Out",
      },
      {
        id: "BID-63",
        name: "Section 305-315",
        price: 85.52,
        image: assets.WaveStage3,
        date: "Sold Out",
      },
      {
        id: "BID-64",
        name: "Section 206-214",
        price: 146.60,
        image: assets.WaveStage4,
        date: "Sold Out",
      },
      {
        id: "BID-65",
        name: "Section 202-205-215-218",
        price: 171.03,
        image: assets.WaveStage5,
        date: "Available",
      },
      {
        id: "BID-66",
        name: "Fan Grandstand",
        price: 293.20,
        image: assets.WaveStage6,
        date: "Sold Out",
      },
      {
        id: "BID-67",
        name: "VIP 1",
        price: 2443.34,
        image: assets.WaveStage1,
        date: "Sold Out",
      },
      {
        id: "BID-68",
        name: "VIP 2",
        price: 3420.67,
        image: assets.WaveStage2,
        date: "Available",
      },
      {
        id: "BID-69",
        name: "VIP 3",
        price: 4398.01,
        image: assets.WaveStage3,
        date: "Available",
      },
    ],
  },
  {
    id: "NFT-07",
    name: "The Weeknd",
    when: "Oct. 04, 2023 - 19h",
    creator: "Estadio El Campín",
    price: "From 51.42",
    description:
      "The Weeknd will be on October at the El Campín stadium in Bogotá with its After Hours Til Dawn Tour, this concert will be the opnening act for his south american tour.",
    image: assets.nft07,
    bids: [
      {
        id: "BID-71",
        name: "Notheast high",
        price: 51.42,
        image: assets.WaveStage1,
        date: "Sold Out",
      },
      {
        id: "BID-72",
        name: "Northwest high",
        price: 51.42,
        image: assets.WaveStage2,
        date: "Sold Out",
      },
      {
        id: "BID-73",
        name: "West high",
        price: 85.52,
        image: assets.WaveStage3,
        date: "Sold Out",
      },
      {
        id: "BID-74",
        name: "Northwest low",
        price: 146.60,
        image: assets.WaveStage4,
        date: "Sold Out",
      },
      {
        id: "BID-75",
        name: "West low",
        price: 171.03,
        image: assets.WaveStage5,
        date: "Available",
      },
      {
        id: "BID-76",
        name: "East high",
        price: 293.20,
        image: assets.WaveStage6,
        date: "Sold Out",
      },
      {
        id: "BID-77",
        name: "East low",
        price: 2443.34,
        image: assets.WaveStage1,
        date: "Sold Out",
      },
      {
        id: "Central-east high",
        name: "VIP 2",
        price: 3420.67,
        image: assets.WaveStage2,
        date: "Available",
      },
      {
        id: "BID-79",
        name: "Platinum",
        price: 4398.01,
        image: assets.WaveStage3,
        date: "Available",
      },
    ],
  },
];

export { NFTData };
